include:
    - docker-compose.scorpio.yml

services:
    # We don't (yet?) need a database.
    mariadb: !reset

    phpfpm:
        image: itkdev/php8.5-fpm:latest
        depends_on: !reset

    nginx:
        volumes:
            - ./.docker/nginx.htpasswd:/etc/nginx/auth/.htpasswd
