networks:
    scorpio:

services:
    scorpio:
        image: scorpiobroker/all-in-one-runner:java-latest
        restart: "no"
        ports:
            - "9090"
        environment:
            - HTTP_EXPOSE=9090:9999
            - DBHOST=scorpio-db
        depends_on:
            - "scorpio-db"
        networks:
            frontend:
            app:
                aliases: [scorpio.local]
            scorpio:
        platform: "linux/amd64"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=frontend"
            - "traefik.http.routers.scorpio_${COMPOSE_PROJECT_NAME:?}.rule=Host(`scorpio.${COMPOSE_DOMAIN:?}`)"

    scorpio-db:
        image: postgis/postgis
        environment:
            - POSTGRES_USER=ngb
            - POSTGRES_PASSWORD=ngb
            - POSTGRES_DB=ngb
        networks:
            - scorpio
        platform: "linux/amd64"
        # https://stackoverflow.com/a/58806511
        command: ["postgres", "-c", "log_statement=all"]
