# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

# This is not a real Symfony route. It's used only to generate NGSI-LD API request example URLs.
ngsi_ld_v1_request:
    path: /ngsi-ld/v1/{path}
    requirements:
        path: !php/const \Symfony\Component\Routing\Requirement\Requirement::CATCH_ALL
